server:
  port: 9090

spring:
  profiles:
    active: dev

  cloud:
    config:
      label: develop
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth2/jwks
          issuer-uri: http://localhost:9090


logging:
  level:
    root: DEBUG
  org:
    hibernate:
      SQL: DEBUG
      type: TRACE
    springframework:
      security: DEBUG
      web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, env, health
  endpoint:
    env:
      post:
        enabled: true