server:
  port: 7070
  address: 127.0.0.6

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/oauth2/jwks
          issuer-uri: http://localhost:9090

springdoc:
  swagger-ui:
    oauth:
      clientId: swagger
      use-pkce-with-authorization-code-grant: true

swagger:
  oauth2:
    authorization-uri: http://localhost:9090/oauth2/authorize
    token-uri: http://localhost:9090/oauth2/token

logging:
  level:
    root: DEBUG
  org:
    hibernate:
      SQL: DEBUG
      type: TRACE
    springframework:
      security: DEBUG
      web: DEBUG